name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: 安装依赖并打包
      run: |
        npm install
        npm run build

    - name: 部署
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
